---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 2.0.1

after_install:
  - gem build funnel_cake_index.gemspec
  - gem install funnel_cake_index

script:
  - bundle exec rake
  - bundle exec rubocop
