#!/usr/bin/env ruby
# frozen_string_literal: true

require "gli"
require "funnel_cake_index"

class App
  extend GLI::App

  program_desc "Wrapper cli app for indexing Funnel Cake app"

  version FunnelCakeIndex::VERSION

  subcommand_option_handling :normal
  arguments :strict

  desc "Ingest files into solr endpoint using funnel_cake traject config"
  arg_name "Combine URL endpoint or Combine file to ingest"
  command :ingest do |c|
    c.desc "Ingest files into SOLR_URL using funnel_cake traject config"
    c.action do |global_options, options, args|

      FunnelCakeIndex::CLI.ingest
    end
  end

  pre do |global, command, options, args|
    # Pre logic here
    # Return true to proceed; false to abort and not call the
    # chosen command
    # Use skips_pre before a command to skip this block
    # on that command only
    true
  end

  post do |global, command, options, args|
    # Post logic here
    # Use skips_post before a command to skip this
    # block on that command only
  end

  on_error do |exception|
    # Error logic here
    # return false to skip default error handling
    true
  end
end

exit App.run(ARGV)
